### ISSUE TITLE
@font-face not loaded on pdf export

### ISSUE THREAD

**Issue by ponychicken** [iainc/iA-Writer-Templates#10]
I am trying to use a custom font. I define it with a @font-face rule. It works fine in the preview. On exporting the fallback font is used. 

Is there a trick to it?

**Comment by antons** [comment]
I could not reproduce the issue. Both local and remote URLs worked well in my testing.

```css
@font-face {
  font-family: 'Proza Libre';
  font-style: normal;
  font-weight: 400;
  src: url('ProzaLibre.woff') format('woff'), 
       url(https://fonts.gstatic.com/s/prozalibre/v1/SSzNV9SQQjzSH8G-hnuYA7rIa-7acMAeDBVuclsi6Gc.woff) format('woff'); 
}
```

Which version of iA Writer are you using?
