### ISSUE TITLE
Shipping template with custom font

### ISSUE THREAD

**Issue by eimantas** [iainc/iA-Writer-Templates#29]
How should I define `@font-face` directive for locally bundled font in the template? I tried the following:

```css
@font-face {
  font-family: "MyFont";
  font-weight: 400;
  font-style: normal;
  src: local("MyFont.otf"); /* This one was with `Contents/Resources/` and `Resources/` prefix */
}
```

But it didn't work. Should I provide font's post-script name or a file name?
